import globals from "globals";

export default [{
    files: ["**/*.js"],
    languageOptions: {
        globals: {
            ...globals.commonjs,
            ...globals.node,
            ...globals.mocha,
            ...globals.browser,
            // VSCode API
            acquireVsCodeApi: "readonly",
            // Global variables shared across webview files
            vscode: "writable",
            EasyMDE: "readonly",
            easyMDE: "writable",
            cm: "writable",
            currentFile: "writable",
            openTabs: "writable",
            files: "writable",
            folders: "writable",
            expandedFolders: "writable",
            editorTitleInput: "writable",
            isTitleEditing: "writable",
            pendingTitleEditFile: "writable",
            autoSaveTimer: "writable",
            autoSaveDelay: "writable",
            lastSavedContent: "writable",
            lastTypingAt: "writable",
            typingGraceMs: "writable",
            lastCheckboxToggleAt: "writable",
            checkboxGraceMs: "writable",
            suppressMarkersUntil: "writable",
            hiddenMarks: "writable",
            codeLineHandles: "writable",
            listLineFlags: "writable",
            lastLineWithFormatting: "writable",
            hiddenUpdateTimer: "writable",
            // Utility functions
            escapeHtml: "readonly",
            formatTitleFromFile: "readonly",
            buildNewRelativeName: "readonly",
            updateEditor: "readonly",
            updateEditorTitle: "readonly",
            startTitleEditing: "readonly",
            finishTitleEditing: "readonly",
            handleRenameResult: "readonly",
            handleFolderMoveResult: "readonly",
            renderTabs: "readonly",
            closeTab: "readonly",
            saveFile: "readonly",
            renderFilesList: "readonly",
            toggleFolder: "readonly",
            openFile: "readonly",
            initEditor: "readonly",
            initEvents: "readonly",
            clearHiddenMarks: "readonly",
            updateHiddenSyntax: "readonly",
            updateListLineFlag: "readonly",
            hideAllContextMenus: "readonly",
            showFileContextMenu: "readonly",
            showFolderContextMenu: "readonly",
            showListContextMenu: "readonly",
            showContextMenu: "readonly",
            createNewFolder: "readonly",
            setVault: "readonly",
            createNewNote: "readonly",
            refreshFiles: "readonly",
            toggleVaultCollapse: "readonly",
            handleDragStart: "readonly",
            handleDragOver: "readonly",
            handleDragEnd: "readonly",
            handleDropOnFolder: "readonly",
            handleFolderDragEnter: "readonly",
            handleFolderDragLeave: "readonly",
            queueAutoSave: "readonly",
            restoreEditorContextSelection: "readonly",
            wrapSelection: "readonly",
            toggleListPrefix: "readonly",
        },

        ecmaVersion: 2022,
        sourceType: "module",
    },

    rules: {
        "no-const-assign": "warn",
        "no-this-before-super": "warn",
        "no-undef": "warn",
        "no-unreachable": "warn",
        "no-unused-vars": ["warn", { "argsIgnorePattern": "^_|^e$" }],
        "constructor-super": "warn",
        "valid-typeof": "warn",
    },
}];