name: バグ報告
description: BunNoteのバグや問題を報告
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        バグ報告ありがとうございます！以下のフォームにご記入いただき、問題の把握と修正にご協力ください。
  - type: textarea
    id: issue-description
    attributes:
      label: 発生した問題
      description: どのような問題が発生したか、本来どう動作すべきかを説明してください。
      placeholder: 問題の詳細を記入してください。
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 再現手順
      description: この問題を再現するにはどうすればよいですか？
      placeholder: |
        1. '...'に移動
        2. '...'をクリック
        3. エラーが表示される
    validations:
      required: true
  - type: checkboxes
    id: reproducible
    attributes:
      label: 再現性の確認
      description: 問題を安定して再現できますか？
      options:
        - label: 同じ手順で問題を再現できることを確認しました
  - type: input
    id: extension-version
    attributes:
      label: BunNoteのバージョン
      description: 使用中のBunNoteのバージョンを記入してください。
      placeholder: 例：1.0.0
    validations:
      required: true
  - type: input
    id: vscode-version
    attributes:
      label: VS Codeのバージョン
      description: 使用中のVS Codeのバージョンを記入してください。
      placeholder: 例：1.95.0
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 使用環境
      description: お使いのOSを選択してください
      multiple: false
      options:
        - Windows 11
        - Windows 10
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (Fedora)
        - Linux (Arch)
        - Linux (その他)
        - その他
    validations:
      required: true
  - type: checkboxes
    id: multiple-platforms
    attributes:
      label: 複数環境での確認
      description: 他の環境でも動作確認を行った場合はチェックしてください
      options:
        - label: 複数の環境でテストし、同様の問題が発生することを確認しました
  - type: textarea
    id: logs
    attributes:
      label: ログ・エラー出力
      description: 開発者コンソール（ヘルプ > 開発者ツールの切り替え）から関連するログやエラーメッセージを貼り付けてください。
      placeholder: ログやエラーメッセージがあれば貼り付けてください。
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: 補足情報
      description: その他、参考になる情報・スクリーンショットなどがあれば追加してください。
      placeholder: 問題の理解に役立つ情報があれば記入してください。
