name: Feature Request
description: Suggest a new feature for BunNote
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like to see.
      placeholder: Describe the feature in detail.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain why this feature would be useful and what problem it solves.
      placeholder: Describe the use case and benefits.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature could be implemented?
      placeholder: Describe your proposed solution or approach.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've thought about.

  - type: checkboxes
    id: existing-check
    attributes:
      label: Have you checked existing issues?
      description: Please check if this feature has already been requested.
      options:
        - label: I have searched existing issues and this feature has not been requested before.
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request.
      placeholder: Any other information that might help us understand your request.
